**Primeiro exemplo de manipulação de dados usando Python Pandas**

Autor: Gabriel Castro

Data: 6 de Fevereiro de 2023

In [46]:
# Importando biblioteca pandas no Python
import pandas as pd

df = pd.read_excel("DadoExemplo.xlsx")

In [47]:
print(df)

       Regiao - Sigla Estado - Sigla  Municipio  \
0                  NE             AL  ARAPIRACA
1                  NE             AL  ARAPIRACA
2                  NE             AL  ARAPIRACA
3                  NE             AL  ARAPIRACA
4                  NE             AL  ARAPIRACA
...               ...            ...        ...
168404             NE             BA     JEQUIE
168405             SE             MG  ITUIUTABA
168406             SE             MG  ITUIUTABA
168407             SE             MG  ITUIUTABA
168408             SE             MG  ITUIUTABA

                                           Revenda      CNPJ da Revenda  \
0                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
1                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
2                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
3                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
4                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
...                                            ...                  ...
168404  COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA   28.629.089/0001-79
168405           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168406           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168407           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168408           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38

                                      Nome da Rua Numero Rua Complemento  \
0                                  RODOVIA AL 220        105       KM 68
1                                  RODOVIA AL 220        105       KM 68
2                                  RODOVIA AL 220        105       KM 68
3                                  RODOVIA AL 220        105       KM 68
4                                  RODOVIA AL 220        105       KM 68
...                                           ...        ...         ...
168404                  AVENIDA T LOT JD TROPICAL         53         NaN
168405  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168406  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168407  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168408  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN

             Bairro        Cep             Produto Data da Coleta  \
0       CANAFISTULA  57302-605            GASOLINA     2021-11-01
1       CANAFISTULA  57302-605              ETANOL     2021-11-01
2       CANAFISTULA  57302-605              DIESEL     2021-11-01
3       CANAFISTULA  57302-605  GASOLINA ADITIVADA     2021-11-01
4       CANAFISTULA  57302-605          DIESEL S10     2021-11-01
...             ...        ...                 ...            ...
168404     TROPICAL  45209-130              ETANOL     2021-12-31
168405     ALVORADA  38307-113            GASOLINA     2021-12-31
168406     ALVORADA  38307-113              ETANOL     2021-12-31
168407     ALVORADA  38307-113          DIESEL S10     2021-12-31
168408     ALVORADA  38307-113  GASOLINA ADITIVADA     2021-12-31

        Valor de Venda  Valor de Compra Unidade de Medida       Bandeira
0                6.799              NaN        R$ / litro  VIBRA ENERGIA
1                5.299              NaN        R$ / litro  VIBRA ENERGIA
2                5.549              NaN        R$ / litro  VIBRA ENERGIA
3                6.899              NaN        R$ / litro  VIBRA ENERGIA
4                5.649              NaN        R$ / litro  VIBRA ENERGIA
...                ...              ...               ...            ...
168404           5.859              NaN        R$ / litro     PETROSERRA
168405           6.580              NaN        R$ / litro         BRANCA
168406           4.740              NaN        R$ / litro         BRANCA
168407           5.448              NaN        R$ / litro         BRANCA
168408           6.580              NaN        R$ / litro         BRANCA

[168409 rows x 16 columns]

In [48]:
display(df)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168404,NE,BA,JEQUIE,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,28.629.089/0001-79,AVENIDA T LOT JD TROPICAL,53,NaN,TROPICAL,45209-130,ETANOL,2021-12-31,5.859,NaN,R$ / litro,PETROSERRA
168405,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,GASOLINA,2021-12-31,6.580,NaN,R$ / litro,BRANCA
168406,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,ETANOL,2021-12-31,4.740,NaN,R$ / litro,BRANCA
168407,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,DIESEL S10,2021-12-31,5.448,NaN,R$ / litro,BRANCA
168408,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,GASOLINA ADITIVADA,2021-12-31,6.580,NaN,R$ / litro,BRANCA

In [49]:
display(df.head(n=15))

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA
5,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA,2021-11-01,7.198,NaN,R$ / litro,VIBRA ENERGIA
6,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,ETANOL,2021-11-01,5.982,NaN,R$ / litro,VIBRA ENERGIA
7,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,DIESEL,2021-11-01,5.974,NaN,R$ / litro,VIBRA ENERGIA
8,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA ADITIVADA,2021-11-01,7.208,NaN,R$ / litro,VIBRA ENERGIA
9,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,DIESEL S10,2021-11-01,5.983,NaN,R$ / litro,VIBRA ENERGIA
10,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,GASOLINA,2021-11-01,7.197,NaN,R$ / litro,BRANCA
11,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,ETANOL,2021-11-01,5.987,NaN,R$ / litro,BRANCA
12,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,DIESEL,2021-11-01,5.978,NaN,R$ / litro,BRANCA
13,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,DIESEL S10,2021-11-01,5.989,NaN,R$ / litro,BRANCA
14,NE,AL,DELMIRO GOUVEIA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,04.431.113/0001-00,AVENIDA CAXANGA,126,NaN,PEDRA VELHA,57480-000,GASOLINA,2021-11-01,7.175,NaN,R$ / litro,BRANCA

In [50]:
#Dataframe.shape -> mostra o tamanho da tabela
#Dataframe.describe() -> mostra as estatisticas mais basicas
display(df.shape)

#só as linhas
print(df.shape[0])

(168409, 16)

168409

In [51]:
#describe -> mostra as estatisticas mais basicas
print(df.describe())

       Valor de Venda  Valor de Compra
count   168409.000000              0.0
mean         6.005184              NaN
std          0.794541              NaN
min          2.849000              NaN
25%          5.339000              NaN
50%          5.859000              NaN
75%          6.699000              NaN
max          8.990000              NaN

In [52]:
#info() -> mostra quais são as colunas e o tipo de cada uma
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168409 entries, 0 to 168408
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     168409 non-null  object
 1   Estado - Sigla     168409 non-null  object
 2   Municipio          168409 non-null  object
 3   Revenda            168409 non-null  object
 4   CNPJ da Revenda    168409 non-null  object
 5   Nome da Rua        168409 non-null  object
 6   Numero Rua         168353 non-null  object
 7   Complemento        35057 non-null   object
 8   Bairro             168043 non-null  object
 9   Cep                168409 non-null  object
 10  Produto            168409 non-null  object
 11  Data da Coleta     168409 non-null  datetime64[ns]
 12  Valor de Venda     168409 non-null  float64
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  168409 non-null  object
 15  Bandeira           168409 non-null  object
dtypes: datetime64[ns](1), float64(2), object(13)
memory usage: 20.6+ MB
None

In [53]:
#Filtra apenas por uma coluna
print(df["Revenda"])

0                               POSTO ARAPIRACA LTDA
1                               POSTO ARAPIRACA LTDA
2                               POSTO ARAPIRACA LTDA
3                               POSTO ARAPIRACA LTDA
4                               POSTO ARAPIRACA LTDA
                             ...
168404    COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA
168405             ABC DISTRIBUICAO DE PETROLEO LTDA
168406             ABC DISTRIBUICAO DE PETROLEO LTDA
168407             ABC DISTRIBUICAO DE PETROLEO LTDA
168408             ABC DISTRIBUICAO DE PETROLEO LTDA
Name: Revenda, Length: 168409, dtype: object

In [54]:
#Aqui criamos um novo dataframe com as colunas que eu quero...
#Cria mais de uma coluna
df2 = df[['Revenda', 'Municipio', 'Produto', 'Valor de Venda', 'Bairro']]

display(df2)

,Revenda,Municipio,Produto,Valor de Venda,Bairro
0,POSTO ARAPIRACA LTDA,ARAPIRACA,GASOLINA,6.799,CANAFISTULA
1,POSTO ARAPIRACA LTDA,ARAPIRACA,ETANOL,5.299,CANAFISTULA
2,POSTO ARAPIRACA LTDA,ARAPIRACA,DIESEL,5.549,CANAFISTULA
3,POSTO ARAPIRACA LTDA,ARAPIRACA,GASOLINA ADITIVADA,6.899,CANAFISTULA
4,POSTO ARAPIRACA LTDA,ARAPIRACA,DIESEL S10,5.649,CANAFISTULA
...,...,...,...,...,...
168404,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,JEQUIE,ETANOL,5.859,TROPICAL
168405,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA,6.580,ALVORADA
168406,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,ETANOL,4.740,ALVORADA
168407,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,DIESEL S10,5.448,ALVORADA
168408,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA ADITIVADA,6.580,ALVORADA

In [55]:
#loc -> localiza uma linha e coluna
#Exibe a 4a. linha
display(df2.loc[9:"JEQUIE"])

,Revenda,Municipio,Produto,Valor de Venda,Bairro
9,AUTO POSTO FREITAS & MAIA LTDA,DELMIRO GOUVEIA,DIESEL S10,5.983,CENTRO
10,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,GASOLINA,7.197,CENTRO
11,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,ETANOL,5.987,CENTRO
12,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,DIESEL,5.978,CENTRO
13,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,DIESEL S10,5.989,CENTRO
...,...,...,...,...,...
168404,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,JEQUIE,ETANOL,5.859,TROPICAL
168405,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA,6.580,ALVORADA
168406,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,ETANOL,4.740,ALVORADA
168407,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,DIESEL S10,5.448,ALVORADA
168408,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA ADITIVADA,6.580,ALVORADA

In [56]:
#Criar um dataframe gas_df contendo
#apenas as 4 colunas (revenda, municipio, produto, valor de venda)
#somente com combustivel sendo gasolina e exibir na tela

gas_df = df2.loc[df['Produto'] == 'GASOLINA']
display(gas_df)

display(gas_df['Valor de Venda'].max())

,Revenda,Municipio,Produto,Valor de Venda,Bairro
0,POSTO ARAPIRACA LTDA,ARAPIRACA,GASOLINA,6.799,CANAFISTULA
5,AUTO POSTO FREITAS & MAIA LTDA,DELMIRO GOUVEIA,GASOLINA,7.198,CENTRO
10,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,GASOLINA,7.197,CENTRO
14,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,GASOLINA,7.175,PEDRA VELHA
19,MARCOS ANTONIO DA SILVA CABRAL,ITACOATIARA,GASOLINA,6.990,CENTRO
...,...,...,...,...,...
168392,AUTO POSTO KM BAURU LTDA,BAURU,GASOLINA,6.199,VILA FALCAO
168394,COOPERCITRUS COOPERATIVA DE PRODUTORES RURAIS,ITUIUTABA,GASOLINA,6.899,MARIA VILELA
168399,VICMAR COMERCIO DE COMBUSTIVEIS E LUBRIFICANTE...,CAMPOS DOS GOYTACAZES,GASOLINA,7.090,PARQUE LEOPOLDINA
168403,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,JEQUIE,GASOLINA,6.799,TROPICAL
168405,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA,6.580,ALVORADA

7.999

In [57]:
#Exibir qual é o posto e municipio da gasolina mais cara do país?
display(gas_df[['Revenda','Municipio', 'Valor de Venda']].max())

Revenda           ZV POSTO DE SERVIÇO LTDA.
Municipio                           XANXERE
Valor de Venda                        7.999
dtype: object

In [58]:
#DataFrame.loc[] com múltiplas condições para filtragem
#Quais são os preços, postos que vendem ETANOL na minha cidade INDAIATUBA

df_etanol = df2.loc[(df2['Produto'] == 'ETANOL') & (df2['Municipio'] == 'INDAIATUBA')]
df_etanol.sort_values(by='Valor de Venda', inplace=True)

display(df_etanol)

/usr/local/lib/python3.8/dist-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

,Revenda,Municipio,Produto,Valor de Venda,Bairro
160592,AUTO POSTO NAMORADA II LTDA.,INDAIATUBA,ETANOL,4.679,PARQUE DAS NACOES
140194,CENTRO AUTOMOTIVO RIVIERA TROPICAL LTDA,INDAIATUBA,ETANOL,4.679,JD. TROPICAL
140661,M.LI COMERCIO DE COMBUSTIVEIS LTDA.,INDAIATUBA,ETANOL,4.699,CENTRO
159497,M.LI COMERCIO DE COMBUSTIVEIS LTDA.,INDAIATUBA,ETANOL,4.699,CENTRO
141167,AUTO POSTO ESPLANADA DE INDAIA LTDA,INDAIATUBA,ETANOL,4.699,JARDIM ESPLANADA
...,...,...,...,...,...
51129,AUTO POSTO CIDADE DO SOL II LTDA,INDAIATUBA,ETANOL,5.599,JARDIM KIOTO I
51138,AUTO POSTO NAMORADA II LTDA.,INDAIATUBA,ETANOL,5.599,PARQUE DAS NACOES
84395,AUTO POSTO NAMORADA II LTDA.,INDAIATUBA,ETANOL,5.599,PARQUE DAS NACOES
65878,AUTO POSTO CIDADE DO SOL II LTDA,INDAIATUBA,ETANOL,5.599,JARDIM KIOTO I
65363,AUTO POSTO INDIANA SELF LTDA.,INDAIATUBA,ETANOL,6.197,PARQUE BOA ESPERANÇA

In [59]:
#Qual a média de  preços dos combustiveis GASOLINA e GASOLINA ADITIVADA do bairro BELA VISTA em SÃO PAULO

df_test = df[['Valor de Venda', 'Produto', 'Bairro', 'Municipio']]
df_test_filter = df_test.loc[(df_test['Municipio'] == 'SAO PAULO') & (df_test['Bairro'] == 'MOOCA') & (df_test['Produto'].isin(['GASOLINA','GASOLINA ADITIVADA']))]
display(df_test_filter)

        Valor de Venda             Produto Bairro  Municipio
11590            5.999            GASOLINA  MOOCA  SAO PAULO
11646            6.199  GASOLINA ADITIVADA  MOOCA  SAO PAULO
11648            6.099            GASOLINA  MOOCA  SAO PAULO
11834            6.899  GASOLINA ADITIVADA  MOOCA  SAO PAULO
11836            6.699            GASOLINA  MOOCA  SAO PAULO
13271            6.499            GASOLINA  MOOCA  SAO PAULO
13342            6.599  GASOLINA ADITIVADA  MOOCA  SAO PAULO
13344            6.399            GASOLINA  MOOCA  SAO PAULO
13730            6.799  GASOLINA ADITIVADA  MOOCA  SAO PAULO
13733            6.599            GASOLINA  MOOCA  SAO PAULO
63246            6.599            GASOLINA  MOOCA  SAO PAULO
63248            6.799  GASOLINA ADITIVADA  MOOCA  SAO PAULO
63300            6.299            GASOLINA  MOOCA  SAO PAULO
63302            6.499  GASOLINA ADITIVADA  MOOCA  SAO PAULO
63341            6.699            GASOLINA  MOOCA  SAO PAULO
63343            6.899  GASOLINA ADITIVADA  MOOCA  SAO PAULO
63345            6.899            GASOLINA  MOOCA  SAO PAULO
63347            6.999  GASOLINA ADITIVADA  MOOCA  SAO PAULO
63365            6.399            GASOLINA  MOOCA  SAO PAULO
65113            6.499            GASOLINA  MOOCA  SAO PAULO
65115            6.699  GASOLINA ADITIVADA  MOOCA  SAO PAULO
66374            6.199            GASOLINA  MOOCA  SAO PAULO
100308           6.799  GASOLINA ADITIVADA  MOOCA  SAO PAULO
100310           6.599            GASOLINA  MOOCA  SAO PAULO
100339           6.499  GASOLINA ADITIVADA  MOOCA  SAO PAULO
100341           6.299            GASOLINA  MOOCA  SAO PAULO
100357           6.899  GASOLINA ADITIVADA  MOOCA  SAO PAULO
100359           6.699            GASOLINA  MOOCA  SAO PAULO
100360           6.999  GASOLINA ADITIVADA  MOOCA  SAO PAULO
100362           6.899            GASOLINA  MOOCA  SAO PAULO
100372           6.399            GASOLINA  MOOCA  SAO PAULO
101983           6.699  GASOLINA ADITIVADA  MOOCA  SAO PAULO
101985           6.499            GASOLINA  MOOCA  SAO PAULO
103242           6.199            GASOLINA  MOOCA  SAO PAULO
103555           6.599            GASOLINA  MOOCA  SAO PAULO
139275           6.799  GASOLINA ADITIVADA  MOOCA  SAO PAULO
139277           6.599            GASOLINA  MOOCA  SAO PAULO
139295           6.299  GASOLINA ADITIVADA  MOOCA  SAO PAULO
139297           5.999            GASOLINA  MOOCA  SAO PAULO
139313           6.799  GASOLINA ADITIVADA  MOOCA  SAO PAULO
139315           6.599            GASOLINA  MOOCA  SAO PAULO
139316           6.999  GASOLINA ADITIVADA  MOOCA  SAO PAULO
139318           6.899            GASOLINA  MOOCA  SAO PAULO
139332           6.299            GASOLINA  MOOCA  SAO PAULO
140718           6.699  GASOLINA ADITIVADA  MOOCA  SAO PAULO
140720           6.499            GASOLINA  MOOCA  SAO PAULO
142001           6.199            GASOLINA  MOOCA  SAO PAULO

In [60]:
print(df_test_filter.mean())

Valor de Venda    6.575596
dtype: float64

<ipython-input-60-67841c1fa4cc>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(df_test_filter.mean())

In [61]:
# Como mostrar média de valor de venda POR COMBUSTIVEL Brasil todo?
media_por_combustivel = df2[['Produto', 'Valor de Venda']].groupby(by='Produto').mean().round(2)

display(media_por_combustivel)

                    Valor de Venda
Produto
DIESEL                        5.38
DIESEL S10                    5.45
ETANOL                        5.46
GASOLINA                      6.71
GASOLINA ADITIVADA            6.86
GNV                           4.39

In [62]:
#Quero adicionar uma coluna de valor booleana no df
#chamado 'Ativo' que, por padrão, vai ser True para 
#TODAS as linhas

df['Ativo'] = True
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168409 entries, 0 to 168408
Data columns (total 17 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     168409 non-null  object
 1   Estado - Sigla     168409 non-null  object
 2   Municipio          168409 non-null  object
 3   Revenda            168409 non-null  object
 4   CNPJ da Revenda    168409 non-null  object
 5   Nome da Rua        168409 non-null  object
 6   Numero Rua         168353 non-null  object
 7   Complemento        35057 non-null   object
 8   Bairro             168043 non-null  object
 9   Cep                168409 non-null  object
 10  Produto            168409 non-null  object
 11  Data da Coleta     168409 non-null  datetime64[ns]
 12  Valor de Venda     168409 non-null  float64
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  168409 non-null  object
 15  Bandeira           168409 non-null  object
 16  Ativo              168409 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(2), object(13)
memory usage: 20.7+ MB

None

In [63]:
# e se eu quiser uma coluna chamada "Obs"
# que preencha automaticamente "MELHOR CIDADE"
#quando o Municipio for INDAIATUBA, SP...

In [64]:
#Exportar para Excel o dataframe com etanol em Indaiatuba...
df_etanol.to_excel("etanol_indaiatuba.xlsx", sheet_name='Etanol em Indaiatuba', index=False)

In [ ]:
#Vamos brincar de grafico
import matplotlib.pyplot as plt


plt.hist(df['Valor de Venda'])
#Vamos colocar um titulo no grafico
plt.title("Preço dos combustveis - Nov/2021")
#Rótulo horizontal e vertical
plt.xlabel('Preço (em reais)')
plt.ylabel("Quantidade de Coletas")

#traça a  linha vermelha tracejada com o preço médio
plt.axvline(df['Valor de Venda'].mean(), color='red', linestyle='dashed', linewidth='1')

#"plota" o gráfico
plt.show()

In [66]:
c_mean = df['Valor de Venda'].groupby(by=df['Produto']).mean()

In [ ]:
#Vou definir a area do grafico
plt.figure(figsize=(10,5))
#plotar o grafico
c_mean.plot(
    kind="barh",
    xlabel='Tipo de Combustivel',
    ylabel='Preço reais/litro',
    color='red'
)
#grid
plt.grid()

#exibe
plt.show()

In [ ]:
plt.figure(figsize=(10,5))

c_mean.plot(kind="barh", 
    ylabel="Combustíveis", 
    xlabel="Preço/litro", 
    color="purple", 
    title="Média dos Preços/litro de cada produto", 
    alpha=0.5)

In [ ]:
display(c_mean)

excel = "Por_litro.xlsx"
c_mean.to_excel(excel, "Sumário")

In [92]:
#vamos personalizar a planlha excel
from openpyxl import load_workbook
from openpyxl.styles import PatternFill, Font, Color, Alignment

#wb = Workbook
wb = load_workbook(excel)

#Pegar a planilha certa... usando o Sheet Name (nome da planilha)

#ws = WorkSheet/ planilha atual, ativa, de trabalho
ws = wb['Sumário']

#Vamos pintar o cabeçalho da tabela de "cinzinha"
cinzinha = PatternFill("solid", fgColor="808080")
coords = ['A1', 'B1']
for coord in coords:
  ws[coord].fill = cinzinha

#Onde o preço do combustivel for maior ou igual a 6,5 reais (6.5) pinta a fonte
#de vermelho e deixa negrito...
MAX_ROW = ws.max_row
num_linha = 2
while(num_linha <= MAX_ROW):
  coord = 'B'+str(num_linha)
  if ws[coord].value > 6.5:
    ws[coord].font = Font(bold=True, color="FF0000")
  num_linha = num_linha + 1

#salvar o excel
wb.save(excel)